# Build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1

#docker run -it -p 8000:5000 -v ${pwd}:/app -w "/app" mcr.microsoft.com/dotnet/core/sdk /bin/bash
#dotnet restore
#dotnet build
#dotnet run
